# Generated by Django 5.0.2 on 2024-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_utilisateur_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etat',
            name='nom_etat',
            field=models.CharField(default='Etat', max_length=50),
        ),
    ]
