# Generated by Django 5.0.2 on 2024-06-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etat_nom_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etat',
            name='montant_net',
        ),
        migrations.RemoveField(
            model_name='etat',
            name='salarie',
        ),
        migrations.CreateModel(
            name='EtatSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=15)),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat', to='api.etat')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarie', to='api.salarie')),
            ],
        ),
    ]
