# Generated by Django 5.0.2 on 2024-06-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_etat_montant_net_remove_etat_salarie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etat',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat_etablissement', to='api.etablissement'),
        ),
    ]
