# Generated by Django 5.0.2 on 2024-06-27 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_etat_date_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='url_fichier',
            field=models.CharField(default='https://docs.google.com/spreadsheets/d/1SDPNRGIVybFcJKJvA4gtIreMJGA86EpiPAlVeTlvYS4', max_length=150),
        ),
        migrations.AlterField(
            model_name='etat',
            name='date_etat',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
