# Generated by Django 5.0.2 on 2024-07-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_etablissement_url_fichier_alter_etat_date_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etat',
            name='cheque',
        ),
        migrations.AddField(
            model_name='cheque',
            name='etat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='api.etat'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='url_fichier',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
