# Generated by Django 5.0.2 on 2024-07-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_etat_cheque_cheque_etat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='etablissement',
        ),
    ]
