# Generated by Django 5.0.2 on 2024-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cheque_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
