# Generated by Django 5.0.2 on 2024-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_banque_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
